placelist = ["Italy", "France", "Australia", "Montrael", "Canada", "China", "Hollywood"]
print(placelist)
print(sorted(placelist))
print(placelist)
print(sorted(placelist, reverse = True))
print(placelist)
placelist.reverse()
print(placelist)
placelist.reverse()
print(placelist)
placelist.sort()
print(placelist)
placelist.sort(reverse = True)
print(placelist)
